lang: fr
title: Site de Maître Sophie Moutot Noce
email: sophie@moutot.fr
phone_number: +33611431705
phone_number_text: 06 11 43 17 05
description: >- 
  Ce site dispense des informations et des conseils à destination des 
  victimes d'accidents corporels.
url: "http://www.mnavocat.fr"
twitter_username: SMNAvocat
linkedin_username: sophiemoutotnoce
google_plus_profile_url: "https://plus.google.com/u/2/108738942293580871499"
map_api_key: "AIzaSyBg5ePLEbSyQqLxLgelQqUTdRmxy4BsIHA"
address:
  about: dans le 1er arrondissement de Paris
  name: Maître Sophie Moutot Noce
  street_address: 9, rue Duphot
  postal_code: 75001
  locality: Paris
  maps_url: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.487830861083!2d2.323341051400032!3d48.867976179186755!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e32f5269295%3A0xc37ade41c0ad0dfb!2sCabinet+de+Ma%C3%AEtre+Sylvie+Vernassiere!5e0!3m2!1sfr!2sfr!4v1520009895226

home_slider:
- slide: Accidents de ski
  unsplash_id: ySQF5oENkrw
  texts:
  - Skieurs et Snowboarders
  - Faites valoir vos droits à indemnisation en cas d'accident
- slide: Accidents de la circulation
  unsplash_id: nHAGNt2rFz8
  texts:
  - Vous avez été renversé sur la voie publique
  - Avez ou sans tiers identifié, nous pouvons vous aider à être indemnisé
- slide: Accidents de vélo
  unsplash_id: RMlGmGSdFpY
  texts:
  - Vous avez eu un accident à vélo
  - Contactez le cabinet pour vous assister dans vos démarches

google_analytics_id: "UA-115311940-1"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
  style: compressed
